DELETE FROM emulator_texts WHERE `key` LIKE 'hween12_fortune%';
DELETE FROM emulator_texts WHERE `key` LIKE 'xmas14_santateller%';
DELETE FROM emulator_texts WHERE `key` LIKE 'wildwest_stocks%';
DELETE FROM emulator_texts WHERE `key` LIKE 'pirate_parrot%';

INSERT INTO emulator_texts VALUES ('hween12_fortune.message.0', 'Scotland, the bonnie bonnie banks of loch lomond, and you can become a baron of sealand was founded by roy bates following a legal battle with the');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.1', 'Many nights i prayed for this, to let my work begin, first we take berlin.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.2', 'But she doesn\'t believe you.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.3', 'I like big butts and i cannot lie.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.4', 'A job today means work tomorrow.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.5', 'Your friend may claim to love you, but really he or them or that which cannot be spoken aloud.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.6', 'You have to believe in life after love.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.7', 'We sent a team to locate it last year, but they never returned.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.8', 'You know the way to stop me, but you don\'t know what he\'s after');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.9', 'You will become a hip-hop beauty queen and be abducted by aliens.');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.10', 'Yes kids, there was piracy long before bitorrent.roy then looked for and he found it and');
INSERT INTO emulator_texts VALUES ('hween12_fortune.message.11', 'He doesn\'t care.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.0', 'That elf and i are just friends.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.1', 'Did you know i have no idea how i\'m going to deliver all these presents.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.2', 'Santa says relax.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.3', 'What do snowmen eat for lunch? ice bergers.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.4', 'It\'s not about what\'s under the tree, it\'s about who\'s around it.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.5', 'Don\'t get your tinsel in a tangle.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.6', 'Close your eyes and listen to the waves.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.7', 'Hoping you have a zen filled holiday season.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.8', 'The seashell is whispering sweet nothings in my ear. oh, its got a crab inside!');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.9', 'Merry fish-mas.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.10', 'Everyday is a surprise.');
INSERT INTO emulator_texts VALUES ('xmas14_santateller.message.11', 'The sound of the ocean brings me inner calm. it also makes me need the bathroom.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.0', 'Never trust a man without spurs on his boots.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.1', 'Mind tightening my belt, i\'ve recently lost a little weight.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.2', 'I call the vulture that took my eye steven mcgillicudy.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.3', 'In the summer the townsfolk put on a puppet show in my pocket. one of my fingers fell off.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.4', 'If you see a cactus running around in circles you tell it i\'m coming for it as soon as i get outta here');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.5', 'Kick off your boots and stay a while.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.6', 'Sometimes i look into the night sky and sing, \"my heart will go on\".');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.7', 'I often dream about swimming in a sea of chocolate milk but then i remember i\'m lactose intolerant and i can\'t swim.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.8', 'I know 83 digits of pi and not one is correct.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.9', 'What i wouldn\'t give to have my ears back.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.10', 'You\'re darn tootin\' right!');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.11', 'I really need to go to the bathroom.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.12', 'I drink my own tears for water.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.13', 'I know 83 digits of pi and not one is correct.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.14', 'The head nurse said to leave me alone...');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.15', 'I\'m selling these fine leather hats.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.16', 'If the glove doesn\'t fit, you must aquit!');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.17', 'It took me years to figure out how to pronounce \"p\" without lips.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.18', 'Life was simpler when i could walk away from my problems.');
INSERT INTO emulator_texts VALUES ('wildwest_stocks.message.19', 'I only took a piece of gum and now they want to flog me!');
INSERT INTO emulator_texts VALUES ('pirate_parrot.message.0', 'Don\'t you go thinking no thoughts about plucking me feathers now i\'ll \'av your eyes out!');
INSERT INTO emulator_texts VALUES ('pirate_parrot.message.1', 'Go bring me a flagon a’ bubble juice, ye scurvy dog!');
INSERT INTO emulator_texts VALUES ('pirate_parrot.message.2', 'Ya land lubber, might be i got a story too tell ya!');
INSERT INTO emulator_texts VALUES ('pirate_parrot.message.3', 'This ol’ sea dog sing ye a sea shanty about the time i took a ship from a unsuspecting little... oh wait, that\'ll be you... soon.');